version: "3"
services:
  nginx:
    image: nginx:1.19.4
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  postgresql:
    image: pgvector/pgvector:pg17
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      # - "./01_dump.sql:/docker-entrypoint-initdb.d/01_dump.sql"
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=bl1nkker

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=bl1nkker@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=@dm1n
      - PGADMIN_LISTEN_PORT=5050
      - PGADMIN_DISABLE_POSTFIX=true
    ports:
      - "5050:5050"

  redis:
    image: redis:5.0.7
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis-data:/data
      - "./redis.conf:/usr/local/etc/redis/redis.conf"
    sysctls:
      - net.core.somaxconn=511
    command: redis-server /usr/local/etc/redis/redis.conf

  api:
    image: blinkker/canvas-proxy-api:0.1.1a5
    command: api
    depends_on:
      - postgresql
      - redis
    ports:
      - "8010:8000"
      - "28888:8888"
    environment:
      DB_HOST: postgresql
      DB_PORT: 5432

  dbinit:
    image: blinkker/canvas-proxy-api:0.1.1a5
    command: dbinit
    depends_on:
      - postgresql
      - redis
    environment:
      DB_HOST: postgresql
      DB_PORT: 5432
  worker:
    image: blinkker/canvas-proxy-api:0.1.1a5
    command: celery-worker
    depends_on:
      - postgresql
      - redis
    environment:
      DB_HOST: postgresql
      DB_PORT: 5432
      REDIS_HOST: redis
  beat:
    image: blinkker/canvas-proxy-api:0.1.1a5
    command: celery-beat
    depends_on:
      - postgresql
      - redis
    environment:
      DB_HOST: postgresql
      DB_PORT: 5432
      REDIS_HOST: redis

volumes:
  postgres-data:
  redis-data:
