version: "3"
services:
  postgresql:
    image: pgvector/pgvector:pg17
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      # - "./01_dump.sql:/docker-entrypoint-initdb.d/01_dump.sql"
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=bl1nkker
    networks:
      - apps

  redis:
    image: redis:5.0.7
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis-data:/data
      - "./redis.conf:/usr/local/etc/redis/redis.conf"
    sysctls:
      - net.core.somaxconn=511
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - apps

  api:
    image: blinkker/canvas-proxy-api:0.1.1a5
    command: api
    depends_on:
      - postgresql
      - redis
    ports:
      - "8010:8000"
      - "28888:8888"
    environment:
      DB_HOST: postgresql
      DB_PORT: 5432
    networks:
      - apps

  dbinit:
    image: blinkker/canvas-proxy-api:0.1.1a5
    command: dbinit
    depends_on:
      - postgresql
      - redis
    environment:
      DB_HOST: postgresql
      DB_PORT: 5432
    networks:
      - apps
  worker:
    image: blinkker/canvas-proxy-api:0.1.1a5
    command: celery-worker
    depends_on:
      - postgresql
      - redis
    environment:
      DB_HOST: postgresql
      DB_PORT: 5432
      REDIS_HOST: redis
    networks:
      - apps
  beat:
    image: blinkker/canvas-proxy-api:0.1.1a5
    command: celery-beat
    depends_on:
      - postgresql
      - redis
    environment:
      DB_HOST: postgresql
      DB_PORT: 5432
      REDIS_HOST: redis
    networks:
      - apps

volumes:
  postgres-data:
  redis-data:

networks:
  apps:
    driver: bridge
