"""added student and student vector tables

Revision ID: 3b9b2f7c0675
Revises: 5f5372966bf5
Create Date: 2025-02-25 17:31:30.827900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '3b9b2f7c0675'
down_revision: Union[str, None] = '5f5372966bf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('firstname', sa.Text(), nullable=False),
    sa.Column('lastname', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('web_id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('web_id'),
    schema='app'
    )
    op.create_table('student_vectors',
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=128), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('web_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['app.students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('embedding'),
    sa.UniqueConstraint('web_id'),
    schema='app'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_vectors', schema='app')
    op.drop_table('students', schema='app')
    # ### end Alembic commands ###
