"""changed hashed_password -> encrypted_password for canvas use

Revision ID: 3c1ed3eb16c2
Revises: 15cd9c84745b
Create Date: 2025-03-03 10:34:30.483423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c1ed3eb16c2'
down_revision: Union[str, None] = '15cd9c84745b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('canvas_users', sa.Column('encrypted_password', sa.String(), nullable=False), schema='app')
    op.drop_column('canvas_users', 'hashed_password', schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('canvas_users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False), schema='app')
    op.drop_column('canvas_users', 'encrypted_password', schema='app')
    # ### end Alembic commands ###
