"""added unique constraint on canvas_user_id for students table

Revision ID: 3ee23692f284
Revises: 4b01a88f9961
Create Date: 2025-04-28 16:49:13.641687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ee23692f284'
down_revision: Union[str, None] = '4b01a88f9961'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'students', ['canvas_user_id'], schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', schema='app', type_='unique')
    # ### end Alembic commands ###
