"""added recognition_history model

Revision ID: adeb34884a4c
Revises: 3ee23692f284
Create Date: 2025-05-12 13:24:29.246882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adeb34884a4c'
down_revision: Union[str, None] = '3ee23692f284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recognition_history',
    sa.Column('student_id', sa.BigInteger(), nullable=True),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('image_file_json', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('recognition_details_json', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('web_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['app.assignments.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['app.students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('web_id'),
    schema='app'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recognition_history', schema='app')
    # ### end Alembic commands ###
