"""added uniq constraint on student_id and assignment_id for attendance

Revision ID: b32a9d509776
Revises: 40e6fb4b7f51
Create Date: 2025-04-21 14:07:30.413584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b32a9d509776'
down_revision: Union[str, None] = '40e6fb4b7f51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_student_assignment_uc', 'attendances', ['student_id', 'assignment_id'], schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_student_assignment_uc', 'attendances', schema='app', type_='unique')
    # ### end Alembic commands ###
