"""fixes for process single attendance

Revision ID: df0a0cca6bd6
Revises: f00615fa9d82
Create Date: 2025-03-07 11:37:16.015971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df0a0cca6bd6'
down_revision: Union[str, None] = 'f00615fa9d82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('course_id', sa.Integer(), nullable=False), schema='app')
    op.alter_column('attendances', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='app')
    op.create_foreign_key(None, 'attendances', 'canvas_courses', ['course_id'], ['id'], source_schema='app', referent_schema='app')
    op.add_column('students', sa.Column('canvas_user_id', sa.Integer(), nullable=False), schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'canvas_user_id', schema='app')
    op.drop_constraint(None, 'attendances', schema='app', type_='foreignkey')
    op.alter_column('attendances', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='app')
    op.drop_column('attendances', 'course_id', schema='app')
    # ### end Alembic commands ###
