"""removed assignment_id from recognition_history

Revision ID: e3bbbd5f5801
Revises: adeb34884a4c
Create Date: 2025-05-12 15:03:44.581318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3bbbd5f5801'
down_revision: Union[str, None] = 'adeb34884a4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('recognition_history_assignment_id_fkey', 'recognition_history', schema='app', type_='foreignkey')
    op.drop_column('recognition_history', 'assignment_id', schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recognition_history', sa.Column('assignment_id', sa.INTEGER(), autoincrement=False, nullable=False), schema='app')
    op.create_foreign_key('recognition_history_assignment_id_fkey', 'recognition_history', 'assignments', ['assignment_id'], ['id'], source_schema='app', referent_schema='app')
    # ### end Alembic commands ###
