"""changed canvas_id type to str for canvas user

Revision ID: e67cfd0326b1
Revises: 3c1ed3eb16c2
Create Date: 2025-03-03 10:35:51.170973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e67cfd0326b1'
down_revision: Union[str, None] = '3c1ed3eb16c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('canvas_users', 'canvas_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False,
               schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('canvas_users', 'canvas_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               schema='app')
    # ### end Alembic commands ###
