"""added 512 and 4096dim columns to student_vector

Revision ID: eee34468778d
Revises: b32a9d509776
Create Date: 2025-04-25 13:00:56.616103

"""

import pgvector
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eee34468778d"
down_revision: Union[str, None] = "b32a9d509776"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "student_vectors",
        sa.Column(
            "embedding_512",
            pgvector.sqlalchemy.vector.VECTOR(dim=512),
        ),
        schema="app",
    )
    op.add_column(
        "student_vectors",
        sa.Column(
            "embedding_4096",
            pgvector.sqlalchemy.vector.VECTOR(dim=4096),
        ),
        schema="app",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("student_vectors", "embedding_4096", schema="app")
    op.drop_column("student_vectors", "embedding_512", schema="app")
    # ### end Alembic commands ###
