"""added assignment groups

Revision ID: fb15572e48d0
Revises: 301832e1f1c8
Create Date: 2025-03-28 15:50:01.217881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb15572e48d0'
down_revision: Union[str, None] = '301832e1f1c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_groups',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('group_weight', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('canvas_assignment_group_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('created_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_date', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('web_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['app.canvas_courses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('web_id'),
    schema='app'
    )
    op.add_column('assignments', sa.Column('assignment_group_id', sa.Integer(), nullable=True), schema='app')
    op.drop_constraint('assignments_course_id_fkey', 'assignments', schema='app', type_='foreignkey')
    op.create_foreign_key(None, 'assignments', 'assignment_groups', ['assignment_group_id'], ['id'], source_schema='app', referent_schema='app')
    op.drop_column('assignments', 'course_id', schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='app')
    op.drop_constraint(None, 'assignments', schema='app', type_='foreignkey')
    op.create_foreign_key('assignments_course_id_fkey', 'assignments', 'canvas_courses', ['course_id'], ['id'], source_schema='app', referent_schema='app')
    op.drop_column('assignments', 'assignment_group_id', schema='app')
    op.drop_table('assignment_groups', schema='app')
    # ### end Alembic commands ###
