"""changed vector dimension 128 -> 192

Revision ID: ffcdad05b663
Revises: 3b9b2f7c0675
Create Date: 2025-02-26 11:36:58.070676

"""

from typing import Sequence, Union
import pgvector
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "ffcdad05b663"
down_revision: Union[str, None] = "3b9b2f7c0675"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "student_vectors",
        "embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=128),
        type_=pgvector.sqlalchemy.vector.VECTOR(dim=192),
        existing_nullable=False,
        schema="app",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "student_vectors",
        "embedding",
        existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=192),
        type_=pgvector.sqlalchemy.vector.VECTOR(dim=128),
        existing_nullable=False,
        schema="app",
    )
    # ### end Alembic commands ###
